#!/bin/bash

. $HOME/automafield/script.sh

for i in `pct_all_instances 1| grep OCG`
do
	pct 1 $i -t -c "\\copy (select '$i',login,date from res_users where active = 't') to STDOUT with CSV "
done

for i in `pct_all_instances 2| grep OCB`
do
	pct 2 $i -t -c "\\copy (select '$i',login,date from res_users where active = 't') to STDOUT with CSV "
done

for i in `pct_all_instances 3| grep OCA`
do
	pct 3 $i -t -c "\\copy (select '$i',login,date from res_users where active = 't') to STDOUT with CSV "
done
