#!/bin/bash

. $HOME/automafield/script.sh

ct=$1
for i in `pct_all_instances $ct`
do
    pct $ct $i -t -c "\\copy (select '$i', 'batch', name, life_date from stock_production_lot where life_date < '1900-01-01') to STDOUT with CSV"
    pct $ct $i -t -c "\\copy (select '$i', 'inv', expiry_date from stock_inventory_line where expiry_date < '1900-01-01') to STDOUT with CSV"
done
