#!/bin/bash

. $HOME/automafield/script.sh

ct=$1
for i in `pct_all_instances $ct`
do
    pct $ct $i -t -c "\\copy (select '$i', name, usage from stock_location where location_category = 'consumption_unit' and active) to STDOUT with CSV"
done
