#!/bin/bash

. $HOME/automafield/script.sh

ct=$1
if [ -z "$ct" ]; then
    echo "missing ct number"
    exit 1
fi

for i in `pct_all_instances $ct | grep -v SYNC_SERVER_LOCAL`
do
    pct $ct $i -t -c "\\copy (SELECT 
  '$i',
  res_users.name, 
  res_groups.name as group
FROM 
  public.res_groups, 
  public.res_users, 
  public.res_groups_users_rel
WHERE 
  res_groups_users_rel.uid = res_users.id AND
  res_groups_users_rel.gid = res_groups.id
order by
  res_users.name) to STDOUT CSV
"
done

