#!/usr/bin/env python

import xmlrpclib

def ctx(l):
    return { 'lang': l }

username = 'admin' #the user
pwd = 'admin'      #the password of the user
dbname = 'HQ1'    #the database
port = 8069

sock_common = xmlrpclib.ServerProxy ('http://localhost:%d/xmlrpc/common' % port)
uid = sock_common.login(dbname, username, pwd)
transport = None
encoding = None
verbose = True
sock = xmlrpclib.ServerProxy('http://localhost:%d/xmlrpc/object' % port, transport, encoding)

prod='DORAALBE4T-'
ids = sock.execute(dbname, uid, pwd, 'product.product', 'search', [ ('default_code', '=', prod) ])
if len(ids) == 0:
	raise RuntimeError("product %s not found" % prod)

pid = ids[0]

fields = ['name']

data = sock.execute(dbname, uid, pwd, 'product.product', 'read', pid, fields, ctx('en_MF'))
print "HQ1 find it in english", data

data = sock.execute(dbname, uid, pwd, 'product.product', 'read', pid, fields, ctx('fr_MF'))
print "HQ1 find it in french", data

# Add a star onto the end
data['name'] = data['name'] + "*"

print "write into french", data
del data['id']
res = sock.execute(dbname, uid, pwd, 'product.product', 'write', pid, data, ctx('fr_MF'))
print "write it in french:", res

