#!/bin/bash

. $HOME/automafield/script.sh

for ct in 1 2 3
do
	for i in `pct_all_instances $ct`
	do
		pct $ct $i -t -c "select '$i',default_code from product_product where default_code like '% %'" | cat
	done
done
