#!/usr/bin/env python

import sys
import xmlrpclib

username = 'admin' #the user
pwd = 'admin'      #the password of the user

host = sys.argv[1]
if not host:
	raise RuntimeError("need host as first argument")
dbname = sys.argv[2]
if not dbname:
	raise RuntimeError("need dbname as 2nd argument")

url='http://%s:8069/xmlrpc' % host
print "connect to", url

sock_common = xmlrpclib.ServerProxy (url + "/common")
uid = sock_common.login(dbname, username, pwd)
transport = None
encoding = None
verbose = True
sock = xmlrpclib.ServerProxy(url + "/object", transport, encoding)

conn_id = sock.execute(dbname, uid, pwd, 'sync.client.sync_server_connection', 'search', [])
print conn_id
res = sock.execute(dbname, uid, pwd, 'sync.client.sync_server_connection', 'connect')
print "connect:", res

res = sock.execute(dbname, uid, pwd, 'sync.client.entity', 'sync')
print "sync:", res
