#!/bin/sh

# A wrapper script to log the output and only let cron see it
# when something goes wrong.

dir=$HOME/logs/`date +%Y%m%d-%H%M`

if [ $# -eq 2 ]; then
    dir=$HOME/logs/$2_`date +%Y%m%d-%H%M`
fi

if [ -d $dir ]; then
    echo "Cannot overwrite log dir $dir."
    exit
fi
mkdir -p $dir

date > $dir/start.txt
$1 > $dir/stdout.txt 2>$dir/stderr.txt
rc=$?
date > $dir/end.txt

if [ $rc != 0 -o -s $dir/stderr.txt ]; then
    echo "Command: $1"
    echo "  -> result code: $rc"
    echo

    echo "stderr:"
    cat $dir/stderr.txt
    echo "----"

    echo
    echo "stdout:"
    cat $dir/stdout.txt
    echo "----"

    echo
    echo "Working directory:" $dir
fi
